### ISSUE TITLE
can you provide the pretrained model

### ISSUE THREAD

**Issue by cltdevelop** [tengshaofeng/ResidualAttentionNetwork-pytorch#10]
Thank you for sharing your code!

can you provide the best pretrained model?

**Comment by tengshaofeng** [comment]
@cltdevelop ， i have uploaded the model for cifar10

**Comment by xk88372527** [comment]
> @cltdevelop ， i have uploaded the model for cifar10

Excuse me, if I want to train my own data, how can I get the pretrained mode? 
Thank you for your answer.
