### ISSUE TITLE
Shouldn't you record grad when testing?

### ISSUE THREAD

**Issue by DevinXYang** [tengshaofeng/ResidualAttentionNetwork-pytorch#14]
https://github.com/tengshaofeng/ResidualAttentionNetwork-pytorch/blob/88ed90f1b59f4b20e152495d3a5b6a19a4aa4232/Residual-Attention-Network/train_mixup.py#L56

When testing, model do not need grad.
And this line caused me out of memory.

**Comment by tengshaofeng** [comment]
你的意思是with torch.no_grad:
images = Variable(images.cuda()) ???

**Comment by DevinXYang** [comment]
@tengshaofeng 不需要Variable

**Comment by tengshaofeng** [comment]
好的

**Comment by tengshaofeng** [comment]
最近在做啥新研究

**Comment by DevinXYang** [comment]
我们把mobilefacenet跑到了论文水平,应该是开源项目的第一个,resnet跑不动就放弃了.

**Comment by tengshaofeng** [comment]
做人脸识别啊？里面用的arcloss还是什么损失函数
