### ISSUE TITLE
下面是我运行某epoch的结果，我想问一下：为什么分类测试精度这么低？

### ISSUE THREAD

**Issue by gden138** [tengshaofeng/ResidualAttentionNetwork-pytorch#17]
Epoch [32/300], Iter [100/254] Loss: 0.2530
Epoch [32/300], Iter [200/254] Loss: 0.1421
the epoch takes time: 40.39500594139099
evaluate test set:
Accuracy of the model on the test images: 87 %
Accuracy of the model on the test images: 0.8785185185185185
Accuracy of plane :  0 %
Accuracy of   car :  0 %
Accuracy of  bird :  1 %
Accuracy of   cat :  0 %
Accuracy of  deer :  0 %
Accuracy of   dog :  3 %
Accuracy of  frog :  0 %
Accuracy of horse :  0 %
Accuracy of  ship :  0 %
Accuracy of truck :  1 %

分类测试精度这么低，还有多个类别都有对应精度？是不是我运行软件的版本有问题，我用python3.5 pytorch1.1版本。还有就是最高精度没输出是咋回事。谢谢！

**Comment by 13331112522** [comment]
我也是这个问题，请问如何解决的？

**Comment by gden138** [comment]
因为分类数比较多，我的40多类，代码判断里面好像是类别精度大于0.01时候才统计显示，所以有些类别显示为0，其实应该是有精度的。




------------------ 原始邮件 ------------------
发件人: "David Zhou"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 晚上10:49
收件人: "tengshaofeng/ResidualAttentionNetwork-pytorch"<ResidualAttentionNetwork-pytorch@noreply.github.com>;
抄送: "yifan"<120828069@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [tengshaofeng/ResidualAttentionNetwork-pytorch] 下面是我运行某epoch的结果，我想问一下：为什么分类测试精度这么低？ (#17)




我也是这个问题，请问如何解决的？

**Comment by tengshaofeng** [comment]
以总的准确率为准，根据你这个看来，应该是每个单独的分类的精度计算有问题，相应改下代码就好了

**Comment by gden138** [comment]
嗯嗯，我大致知道了，我看评论里面已经能实现97以上的精度了，是又加入了哪些技巧呢？能不能共享一下最新结果。谢谢


------------------ 原始邮件 ------------------
发件人: "bojohn"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 下午3:46
收件人: "tengshaofeng/ResidualAttentionNetwork-pytorch"<ResidualAttentionNetwork-pytorch@noreply.github.com>;
抄送: "yifan"<120828069@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [tengshaofeng/ResidualAttentionNetwork-pytorch] 下面是我运行某epoch的结果，我想问一下：为什么分类测试精度这么低？ (#17)




以总的准确率为准，根据你这个看来，应该是每个单独的分类的精度计算有问题，相应改下代码就好了

**Comment by tengshaofeng** [comment]
mixup会提高一个多左右百分点
