### ISSUE TITLE
new() received an invalid combination of arguments

### ISSUE THREAD

**Issue by HowardZhang1994** [tengshaofeng/ResidualAttentionNetwork-pytorch#9]
E   TypeError: new() received an invalid combination of arguments - got (float, int, int, int), but expected one of:
E    * (torch.device device)
E    * (torch.Storage storage)
E    * (Tensor other)
E    * (tuple of ints size, torch.device device)
E    * (object data, torch.device device)

how to fix it? Thanks

**Comment by tengshaofeng** [comment]
you can refer to my closed issue： https://github.com/tengshaofeng/ResidualAttentionNetwork-pytorch/issues/3，  maybe it  works.

**Comment by HowardZhang1994** [comment]
Page not found...

**Comment by tengshaofeng** [comment]
how about：  https://github.com/tengshaofeng/ResidualAttentionNetwork-pytorch/issues/3

**Comment by HowardZhang1994** [comment]
It works! Thanks!
